### ISSUE TITLE
어플 프로토 타입 제작

### ISSUE THREAD

**Issue by haan823** [euphony-io/waple#3]
- [x] 카카오 오븐 사용해서 프로토 타입 제작

**Comment by haan823** [comment]
## 프로토 타입

빠진 부분 없는지 피드백 부탁드립니다~
@zion830 @Kimhaedam 

![01_Untitled](https://user-images.githubusercontent.com/57613635/180204341-a2f7872e-73cb-4155-95f9-11254b1dd590.png)
![02_Untitled 2](https://user-images.githubusercontent.com/57613635/180204345-2b6dd033-c3f5-431a-b852-af29dea2dc61.png)
![03_Untitled 8](https://user-images.githubusercontent.com/57613635/180204346-adcd15e9-0268-45c3-b484-c570cb64d0d8.png)
![04_Untitled 3](https://user-images.githubusercontent.com/57613635/180204348-706a58a0-0e73-449b-acaa-dc687a4cb53c.png)
![05_Untitled 4](https://user-images.githubusercontent.com/57613635/180204351-f8be9b99-3b5f-41fe-ba83-81b0828910b5.png)
![06_Untitled 6](https://user-images.githubusercontent.com/57613635/180204353-f275b43c-3c14-437e-8a59-21a172ad3183.png)
![07_Untitled 5](https://user-images.githubusercontent.com/57613635/180204354-14608fed-7765-452c-b1a8-b7a215c9af4d.png)


### References
- 아이콘은 Flaticon.com의 자료를 사용했습니다.

**Comment by zion830** [comment]
와 대박 벌써!! 👍
디자인은 저도 알못이라 ux상 수정하면 좋을 것 같은점 공유드려요!
* PIN 옆에 선택이라고 표기하면 좋을거같아요
    * `PIN(선택)` 이런식으로요!
* `+` 버튼 좌측에 텍스트를 추가하면 좋을거 같아요
    * `와이파이 정보 추가 [+]` 이런식으로요
* 정보 입력 후 완료 버튼 눌렀을 때 화면 하나 추가하면 좋을 것 같아요!
    * `와이파이 정보 공유 활성화 중...` / 하단에 `공유 중지` 버튼 (클릭시 이전화면으로 돌아감)
* 와이파이 목록 하단에 . . .은 없어도 될거같아요!

**Comment by designe** [comment]
오 카카오 오븐 멋진데요?
상현님 한번 이걸루 10분 세미나 이번주에 한번 해주실 수 있나요? 좋네요 👍

**Comment by Kimhaedam** [comment]
회의 끝난지 두 시간도 안 됐는데 벌써 만드시다니 대단합니다!!😎
와플과 어울리는 꿀색 같기도 하고 메인 색상으로 정했던 노란색이면서도 잘 보이는 색이라 딱 좋은 것 같아요!

- repository명은 `waple`로 기재하였는데 메인화면은 `wapple`이라 둘 중 하나로 통일이 필요해 보입니다!
- PIN 번호를 제공하는 방법이 확정된다면 PIN 입력창 위에 어디서 `PIN을 얻을 수 있는지 간단하게 안내`하면 좋을 것 같아요
    - ex) PIN번호는 음료 구매 후 영수증에서 확인 가능합니다. :)

**Comment by haan823** [comment]
@zion830 @Kimhaedam 피드백 감사합니다 😄 오늘 중으로 변경해서 올려볼게요!

@designe 앗 저도 잘 사용하는건 아니지만 한 번 준비해보겠습니다~ 😆

**Comment by haan823** [comment]
바뀐 기능에 맞게 프로토 타입 수정 완료했습니다~
아래 URL이나 QR코드로 확인 가능합니다!

https://ovenapp.io/view/sAJwA9v7LKBrOtxEhsDpK8SM5vQ0N05Z/10yAX

![image](https://user-images.githubusercontent.com/57613635/180204689-caf8f1dc-15f7-4558-aea1-78205431f7fd.png)

**Comment by zion830** [comment]
와 좋아요!! 👍👍👍 
디발자이시네요...ㅎㅎ 감사합니다!
