### ISSUE TITLE
Sample App Idea 공유

### ISSUE THREAD

**Issue by zion830** [euphony-io/waple#5]
https://github.com/orgs/euphony-io/discussions/categories/ideas

작성해주실 분께서 assign으로 지정하면 될것 같습니다! @haan823 @Kimhaedam @zion830

**Comment by Kimhaedam** [comment]
- [x] 영어로 번역 후 추가

**Comment by Kimhaedam** [comment]
한글로 작성 완료하였습니다! 추후 영어로 작성한 버전도 추가할까 합니다.
https://github.com/orgs/euphony-io/discussions/156

**Comment by zion830** [comment]
@Kimhaedam 정리 너무 잘해주셔서 나중에 이거 waple README.md에 써주셔도 좋을거같아요!!

**Comment by Kimhaedam** [comment]
@zion830 오늘 내로 추가해두겠습니다!😄

**Comment by zion830** [comment]
머지까지 완료 되어서 Close 할게요!!
